<?php exit; ?>
[2020-02-18 20:20:50] ERROR: Form 296 > Mailchimp API error: 400 Bad Request. Invalid Resource. rex4*****@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now
Request: POST https://us3.api.mailchimp.com/3.0/lists/ad6b7dc5fe/members - {"status":"pending","email_address":"rex4*****@gm***.com","interests":{},"merge_fields":{"FNAME":"Mike"},"email_type":"html","ip_signup":"151.80.47.82","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"rex4*****@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now","instance":"0837d09e-c81f-401b-a6d5-471712815c25"}
[2020-03-27 12:53:34] WARNING: Form 296 > wagn*****@gm***.com is already subscribed to the selected list(s)
[2020-03-30 09:25:30] ERROR: Form 296 > Mailchimp API error: 400 Bad Request. Invalid Resource. evdd**************@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now
Request: POST https://us3.api.mailchimp.com/3.0/lists/ad6b7dc5fe/members - {"status":"pending","email_address":"evdd**************@gm***.com","interests":{},"merge_fields":{"FNAME":"Dawn"},"email_type":"html","ip_signup":"151.80.47.82","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"evdd**************@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now","instance":"feeb5436-281f-4b38-9e16-2d83ba5004f7"}
[2020-04-05 06:18:54] ERROR: Form 296 > Mailchimp API error: 400 Bad Request. Invalid Resource. blin*********@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now
Request: POST https://us3.api.mailchimp.com/3.0/lists/ad6b7dc5fe/members - {"status":"pending","email_address":"blin*********@gm***.com","interests":{},"merge_fields":{"FNAME":"Tanya"},"email_type":"html","ip_signup":"151.80.47.82","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"blin*********@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now","instance":"359a5062-639d-4a39-91c1-8c1b7caf423f"}
[2020-05-14 09:10:23] ERROR: Form 296 > Mailchimp API error: 400 Bad Request. Invalid Resource. afar******@ou*****.com has signed up to a lot of lists very recently; we're not allowing more signups for now
Request: POST https://us3.api.mailchimp.com/3.0/lists/ad6b7dc5fe/members - {"status":"pending","email_address":"afar******@ou*****.com","interests":{},"merge_fields":{"FNAME":"Justin"},"email_type":"html","ip_signup":"151.80.47.82","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"afar******@ou*****.com has signed up to a lot of lists very recently; we're not allowing more signups for now","instance":"a329ce1f-4c5e-4ad8-9773-fad4341af8a5"}
